Initial updates for skyd
SkynetLabs/docker-skyd pull request #1
Opened 2021-03-22 22:00 UTC by MSevey

Updating for `skyd`

Plan should be to release this for the first `skyd` release which we believe to be v1.6.0

Some variables will need to stay `sia` named to preserve backwards compatibility with nodes running the previous `docker-sia`.

2021-06-15 18:13 UTC, MSevey commented
@ro-tex I had started this a little bit ago, trying to migrate all our references to skyd vs sia/siad to help avoid confusion in the future as we move farther and farther apart. 

I think all the updates I made are isolated to within docker and the files/folders on disk remain the same `sia-data` for example. But please help me double check.

Also I was removing the old sia docker versions and such to start clean. There was a standing todo I believe from you about the builds we were supporting. I think we can trim those down even more now.

2021-06-21 17:00 UTC, ro-tex reviewed
LGMT.

I've listed couple of things we want to do before starting to use this from `webportal` but now that I think about it, we can merge this as soon as we figure out our build strategy and the do the other things in separate PRs. As long as we implement all of them before switching to it in `webportal` we should be fine.

2021-06-21 17:00 UTC, ro-tex commented on CHANGELOG.md
>  ## 1.5.4 (Sia 1.5.4) - 12th January 2021
I think we can trim this as well. `skyd`-only, all the way. :)

2021-06-21 17:00 UTC, ro-tex commented on Dockerfile
> +    unzip -j "$SKYD_ZIP" "${SKYD_PACKAGE}/siad" -d /sia
I think the consensus about that was that we don't really need binary releases anymore and we can use the approach from the `debug` image where we pull a given tag and build it. This will allow us to utilize Docker Hub's infrastructure and not have any build pipelines of our own. We push a tag to github and they build the full set of images for us. Which will reduce the ARGs above to `ARG SKYD_TAG="v1.6.0"`.

But we need to get a hard decision on this one.

2021-06-21 17:00 UTC, ro-tex commented on Dockerfile
>  ARG SIAD_DATA_DIR="/sia-data"
Hm, `SIA_DATA_DIR` becoming `SKYD_DATA_DIR` and living beside `SIAD_DATA_DIR` becomes increasingly confusing. Do you think people running a portal would need that sort of flexibility or can scrap the dup and use a single argument?

2021-06-21 17:00 UTC, ro-tex commented on Makefile
>  		.
We should get rid of the alpine-based dev image and replace it with the debian-based one. We issued a warning that we'd do it when we release 1.6.0.

2021-06-21 21:24 UTC, MSevey commented on Dockerfile
>  ARG SIAD_DATA_DIR="/sia-data"
oh meant to delete that line. The `/sia-data` was the compact piece so that we didn't cause issues on our portals. Arguement name should all be skyd

2021-06-21 21:26 UTC, MSevey commented on Makefile
>  		.
Should we also just remove the `pi` image was well? I don't think we are supporting someone running a skynet portal on a raspberry pi.

2021-06-21 21:27 UTC, MSevey commented on Dockerfile
> +    unzip -j "$SKYD_ZIP" "${SKYD_PACKAGE}/siad" -d /sia
I think we should capture this in a follow up. We need to align on all of that for skyd v1.6.0 and then for on going portal releases. 
I'll capture it in the action plan as well to not lose sight of it.

2021-06-22 07:29 UTC, ro-tex commented on Makefile
>  		.
I wouldn't exclude it as a viable use case, tbh. It's a decent way to run your own private portal. The only issue with that is that the webportal code doesn't run on a Pi because of one npm module that needs to be compiled natively and I couldn't make that happen when I tried. But other than that I don't see a reason not to run a portal on a Pi. Especially if you want it for mostly reads (so, almost no repairs needed) in order to access censored information.

2021-06-23 17:50 UTC, MSevey commented on Makefile
>  		.
ok, so we can just delete the alpine and dev Dockerfiles then? And we will rename the `dev-debian` to just dev correct?

2021-06-23 17:55 UTC, MSevey commented on Dockerfile
>  ARG SIAD_DATA_DIR="/sia-data"
hmm, I think I'll just leave these for now as Sia. I'm not totally confident on why they are named the way they are so we can come back to this later.

2021-06-25 09:14 UTC, firyx requested changes

2021-06-25 09:14 UTC, firyx commented on HOWTO.md
>  `v1.5.0alpine` and push them as well.
`v1.5.0alpine` tag should be removed.

2021-06-25 10:36 UTC, kwypchlo requested changes
I know it's called "initial" updates but if we merge this, we're breaking the master - I think we should do all the updates in one pull request or at least follow up with fixes and updates and merge them to this branch and then only merge to master when it's all ready.

2021-06-25 10:36 UTC, kwypchlo commented on dev/Dockerfile
> +# NOTE: Leaving as /mnt/sia for backwards compatibility
I think with migration to skyd we can actually drop this legacy backwards compatibility, no better time than now

2021-06-25 10:36 UTC, kwypchlo commented on pi/Dockerfile
> +ARG SKYD_ZIP="${SKYD_PACKAGE}.zip"
this should build from sources

2022-05-20 19:11 UTC, closed without merging